version: 0.2
phases:
  install:
    commands:
      - python -V
      - pip install -r requirements.txt || true
      - pip install -r requirements-dev.txt
  build:
    commands:
      - echo "=== Ruff version & config ==="
      - ruff --version
      - ruff config
      - echo "=== Ruff check (GitHub format) ==="
      - ruff check . --output-format=github
      - echo "=== Black check ==="
      - black --check . || true
      - echo "=== Py compile ==="
      - python -m py_compile lambda_function.py
      - echo "=== Pytest ==="
      - pytest -q
artifacts:
  files:
    - function.zip
