version: 0.2
phases:
  install:
    commands:
      - python -V
      - pip install --upgrade pip
      - pip install -r requirements.txt || true
      - pip install -r requirements-dev.txt
  build:
    commands:
      - ruff check . --output-format=github || true
      - black --check . || true
      - python -m py_compile lambda_function.py
      - echo "=== Set PYTHONPATH to repo root ==="
      - export PYTHONPATH="$CODEBUILD_SRC_DIR:$PYTHONPATH"
      - python -c "import sys, os; print('cwd:', os.getcwd()); print('src in path:', '$CODEBUILD_SRC_DIR' in sys.path)"
      - echo "=== Pytest ==="
      - pytest -q || true   # keep non-blocking for now if you want to merge; remove `|| true` later
artifacts:
  files:
    - function.zip

