version: 0.2
phases:
  install:
    commands:
      - python -V
      - pip install -r requirements.txt || true
  build:
    commands:
      # quick validation check; extend with pytest later
      - python -m py_compile lambda_function.py
      - mkdir -p package
      - cp lambda_function.py package/
      - cd package && zip -r ../function.zip .
artifacts:
  files:
    - function.zip
